### ISSUE TITLE
Define different levels of redundancy and failure safety.

### ISSUE THREAD

**Issue by josephineSei** [SovereignCloudStack/standards#540] opened 2024-03-26 12:35 UTC
As well as for the replication of volumes as for AZs, we have to adress the question what redundancy can look like and what to expect from each mechanism.

This may be just a guide or definition as a baseline for further standards.

**Comment by mbuechse** [comment] 2024-03-26 13:08
I may be mistaken, but this looks like a duplicate of #527.

**Comment by josephineSei** [comment] 2024-03-26 13:14
> I may be mistaken, but this looks like a duplicate of #527.

Ah yes, I'm closing this and put my thought into the other ticket.

**Closed** 2024-03-26 13:14 UTC
Labels: IaaS, standards, SCS is standardized, SCS-VP10
