### ISSUE TITLE
[BUG] SCS 0104-v1 is confusing, since the required image(s) can't easily be seen

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/standards#635] opened 2024-06-14 09:49 UTC
The subject says its all. Neither @garloff nor I were able to see it immediately which image is required.

**Comment by mbuechse** [comment] 2024-06-14 10:05
Closed as duplicate of #534. We're on the case already.

**Closed by mbuechse** 2024-06-14 10:05 UTC
Labels: bug

**Comment by fkr** [comment] 2024-06-17 20:32
thanks @mbuechse for spotting this. - this came up in a meeting that @garloff and I had with colleagues from Cleura and I wanted to make sure to add the issue and did not do any further research while in the meeting.
