### ISSUE TITLE
Write ADR for Container Networking/CNI

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/standards#324] opened 2023-06-30 08:54 UTC
As a KaaS operator, I want to understand exactly what standards my CNI must fulfill by reading the relevant ADR.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by NotTheEvilOne** [comment] 2023-08-28 12:23
So far the following features are required / expected at the date of writing:
- Basic CNI plugin capabilities [1]
- Host based firewall (see also Network Policy)
- Gateway API [2] features HTTPRoute and TLSRoute [3]
- Network Policy [4] [5]

The relevant document may be extended after team review.

[1] https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/
[2] https://gateway-api.sigs.k8s.io/
[3] https://github.com/SovereignCloudStack/issues/issues/311#issuecomment-1658606357
[4] https://github.com/SovereignCloudStack/issues/issues/211#issuecomment-1691124345
[5] https://kubernetes.io/docs/concepts/services-networking/network-policies/#behavior-of-to-and-from-selectors

**Comment by mbuechse** [comment] 2024-10-04 09:58
Is this a duplicate of https://github.com/SovereignCloudStack/standards/issues/769? It sure seems so to me.

**Closed by mbuechse** 2024-10-04 09:58 UTC
Labels: Container, standards, SCS is standardized, SCS-VP06a
